[package]
name = "egui_timeline"
description = "A general timeline widget for egui"
version = "0.1.0"
readme = "README.md"
edition = "2024"

[dependencies]
egui = "0.29.1"
egui_plot = "0.29"
eframe = "0.29"

[[bin]]
name = "timeline_demo"
path = "src/main.rs"
